abbr <buffer> select SELECT
abbr <buffer> from FROM
abbr <buffer> where WHERE
abbr <buffer> and AND
abbr <buffer> or OR
abbr <buffer> not NOT
abbr <buffer> like LIKE
abbr <buffer> table TABLE
abbr <buffer> create CREATE
abbr <buffer> drop DROP
abbr <buffer> delete DELETE
abbr <buffer> insert INSERT
abbr <buffer> update UPDATE
